application: dnsalloc
version: 8
runtime: python
api_version: 1
default_expiration: 3650d

derived_file_type:
- python_precompiled

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media
  static_dir: _generated_media

- url: /.*
  script: djangoappengine/main/main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?cron\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?queue\.yaml
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
